### ISSUE TITLE
Support MSI-X capability

### ISSUE THREAD

**Issue by bjorn3** [rust-osdev/pci_types#11]

**Comment by IsaacWoods** [comment]
Basic support for MSI-X capabilities has been added in the most recent versions :)

Please open further issues / PRs if you need more functionality.

**Comment by bjorn3** [comment]
Thanks!

**Comment by bjorn3** [comment]
I noticed a small oversight in the api. Opened https://github.com/rust-osdev/pci_types/pull/29 to fix it.
